### ISSUE TITLE
having some trouble console logging what is in an input box

### ISSUE THREAD

**Issue by EthanTodd** [EthanTodd/EthanTodd.github.io#2]
for my TTT project I have created an input box within a modal to enter a player's name. I've coded it so that when you hit the enter button after typing your name, the modal disappears and the value within that input box should be console logged (so i can check my work). it is not console logging it nor will it print the text into a box on my DOM either.
my current code is:
`//setting a listener to close player name modal
//and to console.log my input
buttonNameClose1.on("click", function(){
    modalPlayer1.toggle();
    console.log(inputNamePlayer1);
})
buttonNameClose2.on("click", function(){
    modalPlayer2.toggle();
    console.log(inputNamePlayer2);
})`

I've tried moving the console.log above the toggle but that didn't work either. My cursor on the console does move down a line so it is definitely doing something but the input isn't showing up.

**Comment by annarankin** [comment]
Hey Ethan! Where are you grabbing the data from your input box?
