### ISSUE TITLE
How do I use a new font?

### ISSUE THREAD

**Issue by EthanTodd** [EthanTodd/EthanTodd.github.io#3]
I'm trying to use a typewriter font but all the sites I go to only allow me to download it and not link it like google fonts does. Do I need to keep searching for a site that will allow me to link it or how do I use my downloaded typewriter font?

**Comment by annarankin** [comment]
Hey Ethan! You should be able to link to your font the same way you link to your CSS or to a Google font - just replace the Google URL with a link to your font file. I'd put the font file in a `styles` or `assets` folder, then link to it using a relative path.
