### ISSUE TITLE
I'm having trouble launching a modal

### ISSUE THREAD

**Issue by EthanTodd** [EthanTodd/EthanTodd.github.io#4]
I'm using Bootstrap for my external stylesheet and they have their own modals that i am trying to access. I am able to copy their code into my html but the modal won't launch.  this is the code that bootstrap gives for a basic modal:
```<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

```

<div class="modal-content">
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal">&times;</button>
    <h4 class="modal-title">Modal Header</h4>
  </div>
  <div class="modal-body">
    <p>Some text in the modal.</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">enter.</button>
  </div>
</div>
```

  </div>
</div>```
they don't give any css information to enter so i figure that is all coded out on their stylesheet. when i click the button nothing launches though

**Comment by annarankin** [comment]
Hey Ethan, Bootstrap actually uses JavaScript as well to toggle their modals - you'll need to include `bootstrap.js` as well if you want to use them!

**Comment by EthanTodd** [comment]
ok, thank you. I also need help with my css if you have a minute. I have my basic board up and going but i am having some trouble with the hover pseudo tag. 
```.square {
    color: white;
    height: 175px;
    box-sizing: border-box;
    border: 1px dashed gray;
    background-color: #2a2a2a;
    text-align: center;
    vertical-align: middle;
    line-height: 175px
}

.square:hover {
    background-color: 3f3f3f;
}```

Also, i can't find my notes on setInterval and I wanted to pick your brain on that

**Comment by annarankin** [comment]
Hey Ethan, sure thing - shoot me a message on Slack when you get back from lunch and we can talk!
