### ISSUE TITLE
i keep getting a throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by EthanTodd** [EthanTodd/EthanTodd.github.io#5]
I can't figure out why i keep getting this throw er and i am about to toss my computer.

i believe it is pointing to a specific line but i'm not sure- node says this:

Ethans-MacBook-Air:classwork ET$ node tomCruise.js
listening on 3000
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write after end
    at ServerResponse.OutgoingMessage.write (_http_outgoing.js:413:15)
    at /Users/ET/dev/artemis/w05/d03/Classwork/tomCruise.js:29:23
    at Array.forEach (native)
    at Server.<anonymous> (/Users/ET/dev/artemis/w05/d03/Classwork/tomCruise.js:25:24)
    at Server.emit (events.js:110:17)
    at HTTPParser.parserOnIncoming [as onIncoming](_http_server.js:491:12)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:23)
    at Socket.socketOnData (_http_server.js:343:22)
    at Socket.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)

and my code is this:
```    if(path === "/") {

``````
  if (query){
   query = query.split("=");

     if (query[0] === "t"){
       tomCruiseDM.forEach(function(tomMovie){

         if (tomMovie.Title.toLowerCase === query[1].toLowerCase){
         response.writeHead(200, {"Content-Type": "application/json"});
         response.write(JSON.stringify(tomMovie));
         response.end();
         }

       });

     }

   } else {
   response.writeHead(200, {"Content-Type": "text/html"});
   response.write("welcome to tom cruise database")
   response.end();
   }```
``````

**Comment by EthanTodd** [comment]
that is my code surrounding like 29 where i believe the problem is

**Comment by EthanTodd** [comment]
it looks like none of my response.write statements are working properly. i called that variable in the server.on function though.
```server.on('request', function(request, response){ 

```

```

**Comment by EthanTodd** [comment]
I re-typed everything into a new doc and it works ok now. still can't figure out what happened there. would you check my work on the tom cruise file though? i think i did it correct but i'm not sure if i'm missing something.  there were only 4 tasks right? i'll push it- it's called movies.js in my classwork folder for today

**Comment by EthanTodd** [comment]
the same thing is happening on my homework now for some reason. it is on the line where i am asking it to write data.  the lines that look like this:

``` response.write(JSON.stringify(e));```
where i am asking it to stringify.  the first one doesn't create an error though, only the ones that have more than one match.  also, i checked online and the error it is giving me could be attributed to a port that is already in use?  the error is  throw er; // Unhandled 'error' event
```

**Comment by EthanTodd** [comment]
fixed it :)

**Comment by annarankin** [comment]
Hey Ethan, glad to see you fixed it! Want to run through it together at any point?
