### ISSUE TITLE
Anna, I'm having a hard time with the skateboard section

### ISSUE THREAD

**Issue by EthanTodd** [EthanTodd/EthanTodd.github.io#6]
I can't seem to .add_passenger. it is originally written in my Vehicle class as:

`def add_passenger(new_passenger)
        @passengers.push(new_passenger)
        @in_danger = true if @passengers.length > @capacity 
    end`
I am trying to super() call it in my Skateboard class which is a child of Vehicle like this:
`def add_passenger (new_passenger)
        super(new_passenger)
    end`
My error is: 
`[3] pry(main)> my_sweet_deck.add_passenger('PJ')
NoMethodError: undefined method `push' for nil:NilClass`

**Comment by EthanTodd** [comment]
when super() brings in the method from Vehicle, what am I supposed to do with all the other stuff that comes with it?

**Comment by EthanTodd** [comment]
i just created a new method and added passengers into my skateboard initialize to fix it

**Comment by EthanTodd** [comment]
I"m still confused though- further down in the assignment i am being asked to use the .go_to method which is from my parent Vehicle class.  Do i create a new method in skateboard class and the superclass?? or just make a new method in skateboard? the directions didn't say to make that particular method so I am guessing i need to import it somehow from the parent class?

**Comment by annarankin** [comment]
Hey Ethan! So, if Skateboard is inheriting from Vehicle, it will have
access to all of its methods by default. The only time you need to worry
about `super` is if you're overwriting a method and want to keep the
functionality of the parent class's method. Try making the Skateboard class
inherit from Vehicle without even defining any methods inside of it, and
seeing what methods you can call on it (like .go_to)!
